### ISSUE TITLE
Mobile Support

### ISSUE THREAD

**Issue by stef-rausch** [moolmanruan/obsidian-sequence-hotkeys#1]
Please support the mobile versions of Obsidian -- would be handy for the iPad.

Thanks!

**Comment by moolmanruan** [comment]
Hi Stefano, I just set `isDesktopOnly` in the assuming it won't be useful for mobile, but I forgot you could hook up a keyboard. I will set the `isDesktopOnly` to false again, but I unfortunately don't have an iPad to test with.

**Comment by moolmanruan** [comment]
Made the change and made 0.2.3 release.

**Comment by stef-rausch** [comment]
Thanks a lot! I will test it and report back.

**Comment by stef-rausch** [comment]
Works like a charm -- thank you for the plugin!

**Comment by moolmanruan** [comment]
Awesome, glad you find it useful 😄
