### ISSUE TITLE
FR: add time limit on the plugin.

### ISSUE THREAD

**Issue by YIRU69** [moolmanruan/obsidian-sequence-hotkeys#10]
Hello friend. I have a good idea to improve the plugin when I get up early.
Could you try to add a time limit when input sequence hotkeys?
For example, when I input an interval greater than 1s, I ignore the hotkey I entered earlier. This will avoid some unnecessary errors.

**Comment by nhan000** [comment]
I need this too. Please consider implementing it like how [Doubleshift](https://github.com/qwyntex/doubleshift) plugin does.

**Comment by moolmanruan** [comment]
Hi @YIRU69 and @nhan000. Sorry for the slow reply, was a bit busy recently. I'll think about it a bit.

One solution could be to not consume presses if they don't match an ongoing sequence. For example `ctrl-w ctrl-q` is mapped to a command. If you press `ctrl-w` it is consumed and the plugin waits for the next press. Currently if something other than `ctrl-q` is pressed that press is captured and the sequence reset, but instead I could let the next press through normally (if it's not `ctrl-q`) and reset the sequence.

**Comment by moolmanruan** [comment]
Made the change. Let me know if it solves your problems.

**Comment by YIRU69** [comment]
@moolmanruan Hi, I am glad to watch you improve it.
It is great way to solve my problem!

**Comment by lukemt** [comment]
It works just beautifully!
