### ISSUE TITLE
Hide the sequence in the status bar

### ISSUE THREAD

**Issue by nhan000** [moolmanruan/obsidian-sequence-hotkeys#11]
Having this element changing with every keystroke is very distracting especially when it's also moving other elements depending on long/short keystrokes/combinations.
![image](https://user-images.githubusercontent.com/85216095/182528399-ba32671f-514c-4c25-a266-3e6a70e4bcda.png)

Do you have a CSS snippets that hide this element? I think it's better to have an option in the plugin settings or support that option with Style Settings plugin.

Thanks a lot!

**Comment by moolmanruan** [comment]
Hi @nhan000, yeah I can remove that or make it optional. Will let you know once it's done.

**Comment by moolmanruan** [comment]
@nhan000, I made the change and released 0.5.1
