### ISSUE TITLE
It seems the trigger key cannot be repeated

### ISSUE THREAD

**Issue by huyz** [moolmanruan/obsidian-sequence-hotkeys#12]
I wanted to create a hotkey `⌥T ⌥T` but that doesn't work right.

Not a big deal though. I can pick another sequence.

**Comment by moolmanruan** [comment]
Hi @huyz, will have a look this week and fix it if I can reproduce.

**Comment by moolmanruan** [comment]
I had a look and can't seem to reproduce the issue. Does it happen on your system with any repeated chord?

**Comment by huyz** [comment]
I have other issues that I probably should resolve before tackling this one.  Mainly conflicts with vim keybindings.  I still can't get this to work for the general case. Once I'm done with that, I'll revisit this issue.

**Comment by moolmanruan** [comment]
Cool, I'll close it for now. Feel free to open another issue once you've sorted out the other issues and still feel that there's a bug.
