### ISSUE TITLE
Not working right if second key of the sequence is already mapped as a hotkey

### ISSUE THREAD

**Issue by drventure** [moolmanruan/obsidian-sequence-hotkeys#13]
First off, excellent plugin! Really would be nice if Obsidian supported this natively.

Just wanted to let you know that I've run into an issue. It's minor but....

Basically, if I want to define a sequence, say Ctrl-K+Ctrl_H, but Ctrl-H is already mapped as a hotkey in Obsidian, it doesn't work. Or rather, if I press Ctrl-K, and then, as soon as I press Ctrl-H, the sequence handling stops and the Action assigned to Ctrl-H runs.

However, I thought maybe if I unassigned Ctrl-H in the main hotkeys area and assign it in the SequenceHotkeys config, that might work. Sure enough, it does. So there's a pretty simple workaround, which is good.

Just wanted you to know

**Comment by moolmanruan** [comment]
Hi @drventure, I agree that it would be a nice native feature.
Yes, it's a known issue (mentioned in the readme). Best I can do on my side is try and detect the clash and show it, but I wouldn't want to update the base config in any way.
And yes, as you mentioned the proper workaround is to just assign the same thing in the plugin 😄
