### ISSUE TITLE
The trigger key hijacked my input

### ISSUE THREAD

**Issue by pasiooooo** [moolmanruan/obsidian-sequence-hotkeys#16]
The plugin will hijack my typing. 

For example, if I set TL to turn off the left sidebar, then when I am in edit view I cannot type the letter T.

**Comment by moolmanruan** [comment]
Hi @jiazhanhe, the plugin consumes key presses if they are part of the sequence, thus I would recommend using keys with modifiers.
I'll think about adding a setting that lets key presses through even if they are part of a sequence.

**Comment by pasiooooo** [comment]
Thank you and I look forward to your great work!
