### ISSUE TITLE
[ FR ] Multiple Sequence Hotkeys for One Command

### ISSUE THREAD

**Issue by stef-rausch** [moolmanruan/obsidian-sequence-hotkeys#2]
What about having the option to bind different sequence hotkeys to one command?

The core Hotkeys settings allows assigning as many combinations as one wants, which is very convenient if different keyboards are used. In my case I use an HP Elite laptop with Windows and the Apple iPad: the `CTRL` and the `ALT` / `OPT` keys are not in the same spot. For ease of execution I have assigned both the `CTRL` and the `ALT` / `OPT` variant to the same command.

Thank you for considering.

**Comment by moolmanruan** [comment]
Yeah, sure.

**Comment by moolmanruan** [comment]
Changes made and released 0.3.0

**Comment by stef-rausch** [comment]
Thank you!
