### ISSUE TITLE
[FR] Declutter view

### ISSUE THREAD

**Issue by AtlcatlQ** [moolmanruan/obsidian-sequence-hotkeys#24]
I love this plugin, but i have a lot of commands

So I would like to see only the commands that i have binded to a sequence. I find would be quite useful if you could filter the non-asigned commands from the asigned ones. 

Like: 
- [ ] Only show the Sequence Asigned commands
- [ ] Show All commands
- [ ] Filter by Name (With the search function)

**Comment by moolmanruan** [comment]
Hi @AtlcatlQ, I'll have a look. I saw that the default hotkeys settings view allows for the functionality, so will try and copy that for now.

**Comment by ruan-rr** [comment]
Hi @AtlcatlQ, forgot to reply to this issue again, but the changes have been made a while ago and is released.

**Comment by moolmanruan** [comment]
Hi @AtlcatlQ, forgot to reply to this issue again, but the changes have been made a while ago and is released.
