### ISSUE TITLE
[ FR ] Chained Commands' Execution

### ISSUE THREAD

**Issue by stef-rausch** [moolmanruan/obsidian-sequence-hotkeys#3]
What about having the option to invoke several [ chained ] commands with one -- or alternative [ see #2 ] -- sequence hotkey?

The addition would make it possible to build complex "micro" workflows -- aka macros -- and elevate the plugin to the next level. It would be the natural next [ evolutionary ] step making other "hacks" obsolete.

Thank you for considering.

**Comment by moolmanruan** [comment]
Thanks for the suggestion. I am considering it, I'm just worried that it will blow up the scope of the plugin. Maybe it can be a separate plugin that you can use to build the sequence of command and use this plugin to assign a shortcut to it.

**Comment by moolmanruan** [comment]
Hi Stefano, I've found this macro plugin (obsidian://show-plugin?id=macro-plugin). Could you see if that combined with my plugin solves your problem?

**Comment by stef-rausch** [comment]
Additionally, `QuickAdd` is another possibility which works.

I just need to install another plugin to achieve the result and I would like to keep the number of installed plugins at a minimum. :wink: 

Thanks nevertheless for looking into it.

**Comment by moolmanruan** [comment]
Awesome, I'm glad it works. Sorry for the inconvenience, though.
