### ISSUE TITLE
(Not an issue) This plugin is freaking fantastic!  🎉

### ISSUE THREAD

**Issue by akaalias** [moolmanruan/obsidian-sequence-hotkeys#6]
Hey there, I wasn't sure where else to post this (feel free to close right away)

In short: This plugin is FREAKING FANTASTIC!

I'm a long-time Emacs-user it allows me to create a few essential, deeply engrained sequences that I've missed for years now.

- Split Vertical Control-x-3
- Split Horizontal Control-x-2
- Focus buffer Control-x-1
- Move focus to other buffer  Control-x-o
- Open file Control-x-f / Control-x-b

Thank you!

**Comment by YIRU69** [comment]
@akaalias  Correct! I love this plugin so much! I find the plugin in https://www.obsidianroundup.org/2022-06-04/.

**Comment by moolmanruan** [comment]
Glad you enjoy it 😄 Yeah, I also use Emacs-like shortcuts and made the plugin because I need to use the same shortcuts for similar actions in different apps.
