### ISSUE TITLE
[Feature Request] Support for SHIFT as Hotkey

### ISSUE THREAD

**Issue by FelipeRearden** [moolmanruan/obsidian-sequence-hotkeys#8]
Hello @moolmanruan !!!!!

First of all, thank you very much for this amazing plugin !!!!

As someone that uses Obsidian only with keyboard for 95% of my workflow, this is a dream 💙

## My FR

It’s a simple FR to explain : would be amazing to be able to use `SHIFT` as a hotkey the same way that we have support for `ENTER` and `ESC`  :)

- I wanna use `SHIFT + SHIFT + SHIFT` to open Quick Switcher  

## Question of SHIFT

If you agree to implement this feature, I would like to ask if would be possible to have support `SHIFT LEFT` and `SHIFT RIGHT`

- Would be amazing to be able to define two different hotkeys for each key :)

---

Thanks for reading this !!!!! I hope you like my suggestion 🙏 🙏 🙏

Let me know if you need more information !!!

Have a great day 🌞

**Comment by moolmanruan** [comment]
Hi @FelipeRearden, sounds like a good feature to support. I actually didn't consider that shift gets pressed on it's own in sequences sometimes, since it's also considered a modifier.

**Comment by FelipeRearden** [comment]
> Hi @FelipeRearden, sounds like a good feature to support. I actually didn't consider that shift gets pressed on it's own in sequences sometimes, since it's also considered a modifier.

Hello @moolmanruan !!!!

Thank you very much for your reply !

I'm glad to know that you liked my FR :)

I like to add a triple SHIFT to my keyboard hotkeys because my finger is always next to this key 
- It's fast to hit and to invoke a command :)

---

🙏 I Hope you find a way to differentiate between `SHIFT RIGHT` and `SHIFT LEFT` as well 

I would use a `SHIFT RIGHT + SHIFT RIGHT` to cycle between open panes :)

---

Have a great day!!!!

**Comment by moolmanruan** [comment]
I've added support for the `Shift Shift` shortcut with version __0.4.0__. Please test  it out and let me know if there's any issues. I don't support left and right shift together yet.

**Comment by FelipeRearden** [comment]
> I've added support for the `Shift Shift` shortcut with version __0.4.0__. 

Thank you very much @moolmanruan !!!!!

> Please test  it out and let me know if there's any issues. 

Working perfect on version `0.4.0` 
- Obsidian `0.14.6`
- Obsidian Mobile `1.2.0` on iPadOS 15.4 

I am preparing to update my vaults until the end of this week to the new public version `0.14.15` and `1.2.3` 
- I will comment on this FR when I do this :)

> I don't support left and right shift together yet. 

Thank you very much for conserving LEFT and RIGHT in one of the next versions :)

ℹ️ Let me know if you want me to create a **new Issue for LEFT/Right** and _close this one_. 

---

Thank you very much for this amazing feature !

Have a great day!!!

**Comment by moolmanruan** [comment]
Hi @FelipeRearden, I'm going to close this issue. Feel free to open another one for the left+right shift one.

**Comment by FelipeRearden** [comment]
> Hi @FelipeRearden, I'm going to close this issue.

100% Agree @moolmanruan !!!!

> Feel free to open another one for the left+right shift one.

Thanks @moolmanruan . Done at #20 

Have a great day!!!!
